[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/v1/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/v1/news"
  to = "/.netlify/functions/news"
  status = 200

[[redirects]]
  from = "/api/v1/tape"
  to = "/.netlify/functions/tape"
  status = 200

[[redirects]]
  from = "/api/v1/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
