[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/v1/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/v1/news"
  to = "/.netlify/functions/news"
  status = 200

[[redirects]]
  from = "/api/v1/tape"
  to = "/.netlify/functions/tape"
  status = 200

[[redirects]]
  from = "/api/v1/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/v1/calendar"
  to = "/.netlify/functions/calendar"
  status = 200

[[redirects]]
  from = "/api/v1/headlines"
  to = "/.netlify/functions/headlines"
  status = 200

[[redirects]]
  from = "/api/v1/tracker"
  to = "/.netlify/functions/tracker"
  status = 200

[[redirects]]
  from = "/api/v1/strategies"
  to = "/.netlify/functions/strategies"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
